import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: 60,
        backgroundColor: '#fff',
    },
    headerLogo: {
        width: 40,
        height: 40,
        resizeMode: 'contain',
    },
    content: {
        flex: 1,
        padding: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: '600',
        color: '#333',
        marginBottom: 20,
    },
    sidebar: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 300,
        backgroundColor: '#fff',
        zIndex: 1000,
    },
    sidebarHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: 60,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    sidebarTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#5b6af5',
        marginTop: 0,
    },
    sidebarItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    sidebarItemText: {
        fontSize: 16,
        marginLeft: 15,
        color: '#444',
        fontWeight: '500',
    },
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        zIndex: 999,
    },
    sidebarContent: {
        flex: 1,
        paddingTop: 0,
    },
    sidebarFooter: {
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        padding: 20,
    },
    userInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    userTextContainer: {
        marginLeft: 15,
        flex: 1,
    },
    userName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    userEmail: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    logoutMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff5f5',
        padding: 12,
        borderRadius: 12,
    },
    logoutText: {
        marginLeft: 12,
        color: '#ff6b6b',
        fontSize: 16,
        fontWeight: '600',
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        height: 40,
    },
    logoImage: {
        width: 32,
        height: 32,
        marginRight: 12,
        borderRadius: 8,
    },
    logoutButton: {
        backgroundColor: '#ffe5e5',
        padding: 10,
        borderRadius: 12,
    },
    activityContainer: {
        marginTop: 20,
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
    },
    subtitle: {
        fontSize: 16,
        color: '#666',
        marginTop: 5,
    },
    activityGrid: {
        marginTop: 15,
    },
    activityDay: {
        flex: 1,
        aspectRatio: 1,
        margin: 4,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#eee',
    },
    studiedDay: {
        backgroundColor: '#e8f5e9',
        borderColor: '#4CAF50',
        borderWidth: 1,
    },
    today: {
        borderColor: '#5b6af5',
        borderWidth: 2,
    },
    futureDay: {
        opacity: 0.5,
    },
    activityDayText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '500',
    },
    studiedDayText: {
        color: '#4CAF50',
        fontWeight: '600',
    },
    todayText: {
        color: '#5b6af5',
        fontWeight: '700',
    },
    checkIcon: {
        position: 'absolute',
        bottom: 4,
        right: 4,
        color: '#4CAF50',
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 24,
        marginTop: 10,
    },
    statCard: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 20,
        alignItems: 'center',
        flex: 1,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
    statNumber: {
        fontSize: 28,
        fontWeight: '700',
        color: '#333',
        marginTop: 8,
    },
    statLabel: {
        fontSize: 14,
        color: '#666',
        marginTop: 4,
        fontWeight: '500',
    },
    motivationalContainer: {
        backgroundColor: '#f0f3ff',
        borderRadius: 12,
        padding: 16,
        marginBottom: 20,
        borderLeftWidth: 4,
        borderLeftColor: '#5b6af5',
    },
    motivationalText: {
        fontSize: 16,
        color: '#5b6af5',
        fontWeight: '600',
    },
}); 