import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f9fa',
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: 60,
        backgroundColor: '#fff',
    },
    inputContainer: {
        padding: 20,
        backgroundColor: '#fff',
    },
    input: {
        backgroundColor: '#f8f9fa',
        padding: 18,
        borderRadius: 16,
        marginBottom: 15,
        fontSize: 16,
        color: '#444',
    },
    timeInput: {
        height: 50,
    },
    addButton: {
        backgroundColor: '#5b6af5',
        padding: 16,
        borderRadius: 16,
        alignItems: 'center',
    },
    logoutButton: {
        backgroundColor: '#ffe5e5',
        padding: 10,
        borderRadius: 12,
    },
    logoutButtonText: {
        color: '#ff6b6b',
        fontWeight: '600',
    },
    buttonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    listContainer: {
        flex: 1,
        padding: 20,
    },
    reminderContainer: {
        backgroundColor: '#fff',
        padding: 16,
        borderRadius: 16,
        marginBottom: 12,
        marginHorizontal: 2,
    },
    reminderContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    reminderText: {
        fontSize: 16,
        color: '#444',
        flex: 1,
        marginLeft: 12,
        marginRight: 12,
        lineHeight: 22,
    },
    reminderTimeContainer: {
        alignItems: 'center',
        backgroundColor: '#eef0ff',
        padding: 12,
        borderRadius: 12,
        minWidth: 90,
    },
    reminderDay: {
        fontSize: 12,
        color: '#5b6af5',
        fontWeight: '600',
        textTransform: 'uppercase',
        marginBottom: 2,
    },
    reminderDate: {
        fontSize: 16,
        color: '#5b6af5',
        fontWeight: 'bold',
        marginBottom: 2,
    },
    reminderTime: {
        fontSize: 14,
        color: '#5b6af5',
        fontWeight: '500',
    },
    reminderActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    editButton: {
        backgroundColor: '#eef0ff',
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    deleteButton: {
        backgroundColor: '#ffe5e5',
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    updateButton: {
        backgroundColor: '#4CAF50',
    },
    cancelButton: {
        backgroundColor: '#666',
        padding: 15,
        borderRadius: 8,
        alignItems: 'center',
        marginTop: 10,
    },
    datePickerButton: {
        backgroundColor: '#fff',
        padding: 15,
        borderRadius: 12,
        marginBottom: 15,
    },
    datePickerContent: {
        flexDirection: 'column',
    },
    datePickerLabel: {
        fontSize: 14,
        color: '#666',
        marginBottom: 4,
    },
    datePickerButtonText: {
        fontSize: 16,
        color: '#333',
        fontWeight: '600',
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    calendarModalContainer: {
        backgroundColor: 'white',
        borderRadius: 20,
        padding: 20,
        width: '90%',
        maxHeight: '90%',
    },
    calendarHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
        paddingHorizontal: 5,
    },
    calendarTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#333',
    },
    timePickerContainer: {
        marginTop: 15,
        paddingTop: 15,
    },
    timePickerLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
        marginBottom: 8,
    },
    timePickerButton: {
        backgroundColor: '#f8f9fa',
        padding: 15,
        borderRadius: 10,
        alignItems: 'center',
    },
    timePickerButtonText: {
        fontSize: 18,
        color: '#788eec',
        fontWeight: '600',
    },
    closeButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#f5f5f5',
        justifyContent: 'center',
        alignItems: 'center',
        marginLeft: 10,
    },
    closeButtonText: {
        fontSize: 20,
        color: '#666',
        fontWeight: '500',
    },
    confirmDateButton: {
        backgroundColor: '#788eec',
        padding: 16,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: 20,
        marginHorizontal: 5,
        position: 'absolute',
        bottom: 20,
        left: 20,
        right: 20,
    },
    confirmDateButtonText: {
        color: '#ffffff',
        fontSize: 18,
        fontWeight: '600',
    },
    calendarAndTimeContainer: {
        marginBottom: 70,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    emptyText: {
        fontSize: 20,
        color: '#5b6af5',
        marginBottom: 8,
        fontWeight: '600',
    },
    emptySubText: {
        fontSize: 16,
        color: '#888',
        textAlign: 'center',
        lineHeight: 22,
    },
    sidebar: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 300,
        backgroundColor: '#fff',
        zIndex: 1000,
        elevation: 5,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    sidebarHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        paddingTop: 60,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    sidebarTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: '#5b6af5',
    },
    sidebarItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    sidebarItemText: {
        fontSize: 16,
        marginLeft: 15,
        color: '#444',
        fontWeight: '500',
    },
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        zIndex: 999,
    },
    sidebarContent: {
        flex: 1,
    },
    sidebarFooter: {
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
        padding: 20,
    },
    userInfo: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 20,
    },
    userTextContainer: {
        marginLeft: 15,
        flex: 1,
    },
    userName: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    userEmail: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    logoutMenuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff5f5',
        padding: 12,
        borderRadius: 12,
    },
    logoutText: {
        marginLeft: 12,
        color: '#ff6b6b',
        fontSize: 16,
        fontWeight: '600',
    },
    logoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    logoImage: {
        width: 32,
        height: 32,
        marginRight: 12,
        borderRadius: 8,
    },
    headerLogo: {
        width: 40,
        height: 40,
        resizeMode: 'contain',
    },
    importanceContainer: {
        marginTop: 15,
        marginBottom: 20,
    },
    importanceLabel: {
        fontSize: 16,
        color: '#666',
        marginBottom: 8,
    },
    importanceButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    importanceButton: {
        flex: 1,
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        alignItems: 'center',
    },
    importanceButtonActive: {
        borderWidth: 0,
    },
    importanceButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#666',
    },
    activitySummary: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginBottom: 20,
    },
    summaryHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    summaryTitle: {
        fontSize: 18,
        fontWeight: '600',
        color: '#333',
    },
    viewAllButton: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    viewAllText: {
        fontSize: 14,
        color: '#5b6af5',
        marginRight: 4,
    },
    statsRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    statItem: {
        flex: 1,
        alignItems: 'center',
        paddingHorizontal: 8,
    },
    statNumber: {
        fontSize: 20,
        fontWeight: '700',
        color: '#5b6af5',
        marginBottom: 4,
    },
    statLabel: {
        fontSize: 12,
        color: '#666',
        textAlign: 'center',
    },
    greetingSection: {
        paddingHorizontal: 20,
        paddingVertical: 24,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    greeting: {
        fontSize: 28,
        fontWeight: '700',
        color: '#333',
        marginBottom: 6,
    },
    greetingSubtext: {
        fontSize: 16,
        color: '#666',
    },
    activityOverviewContainer: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        marginHorizontal: 20,
        marginTop: 20,
        marginBottom: 24,
        shadowColor: '#000',
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 3,
        elevation: 3,
    },
});
